### ISSUE TITLE
Add Redis Container 

### ISSUE THREAD

**Issue by chinathaip** [stamford-syntax-club/infra#36]
### Story
The backend team(me XD) [would like to do server-side caching](https://github.com/stamford-syntax-club/stamfordcenter-backend/issues/8) for some certain APIs. 

To do so, they need to connect to Redis - which we currently don't have it running at the moment.

### Task
Our task as the platform team is to deploy Redis to the development server using Docker for the backend team to connect to.

@jonathangyi :  - **_DONE_**
- In Infra repository, please create a new folder called 'redis'
- Write a docker-compose.dev.yaml file with a service called `redis`. 
    - This is the image I want you to use: https://hub.docker.com/_/redis/tags. 
- Map host port 6379 to container port 6379 (Don't forget to add this to "used port" list in README.md)
- Set the docker network to be `haproxy_stamford` so that our reverse-proxy can redirect traffic to our redis

Your docker compose file should look something like this:
```yaml
version: "3.8"
networks:
  stamford:
    external: true
    name: haproxy_stamford

services:
  <service-name>:
    image: <redis-image>
    restart: on-failure
    ports:
      - <host-port>:<container-port>
    networks:
      - stamford
```
You can run  typing the following command in the terminal
```bash
docker compose -f haproxy/docker-compose.dev.yaml up -d && docker compose -f redis/docker-compose.dev.yaml up -d
```
To test the connection, we can use a redis extension in VSCode: maybe try searching for this one: `Dunn.redis`
